Repository penaagp-dev/learn-gitflow, pull requests merged in 2023-07, with the labels that each got.

#1 Create profile dokumentasi
  wandi-change.md
Labels: development

#4 fortinaiti ila babaji
  tola.md
Labels: production

#5 Pbi 1 dev
  Dev.html
Labels: development

#7 changes_2
  tola.md
Labels: development

#14 Add: create new file
  oned-code.md
Labels: development

#15 Add: create new file
  oned-code.md
Labels: production

#17 Pbi 22 tola dev
  tola.md
Labels: development

#20 Create: new file for combine action
  combine-tola-wandi.md
Labels: production

#24 Ft ipkin9 task 04 dev
  combine-tola-wandi.md
Labels: development

#25 Modify: add new description
  combine-tola-wandi.md
Labels: production

#33 Ft ipkin9 task 05 dev
  abu.md
Labels: development

#34 Modify: Edit abu.md
  abu.md
Labels: production

#31 Pbi 212 tola dev
  combine-tola-wandi.md
Labels: development

#36 Pbi 232 tola dev
  oned-code.md
Labels: development

#38 changes oned files
  oned-code.md
Labels: production

#40 Pbi 2021 oned dev
  tola.md
Labels: development

#41 changed tola md
  tola.md
Labels: enhancement

#42 Pbi 2021 oned
  tola.md
Labels: production
